import { Lesson } from "@/core/types";

const lessons: Lesson[] = [
  {
    id: 1,
    index: 1,
    paths: ["apache", "apache_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "apache_commandes_utiles",
    course_id: 1,
    description:
      "Commandes principales pour administrer et configurer le serveur Apache.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 2,
    index: 2,
    paths: ["apache", "installer_apache.mdx"],
    label: "Installer Apache",
    slug: "installer_apache",
    course_id: 1,
    description:
      "Procédure d'installation et de vérification d'Apache sur Ubuntu.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 3,
    index: 3,
    paths: ["apache", "virtual_host.mdx"],
    label: "Virtual Host",
    slug: "virtual_host",
    course_id: 1,
    description:
      "Guide sur la création et la gestion des Virtual Hosts dans Apache.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 4,
    index: 4,
    paths: ["apache", "htpasswd.mdx"],
    label: "Restriction .htpasswd",
    slug: "htpasswd",
    course_id: 1,
    description:
      "Mise en place d'une authentification basique avec un fichier .htpasswd.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 5,
    index: 1,
    paths: ["docker", "docker_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "docker_commandes_utiles",
    course_id: 2,
    description:
      "Commandes principales pour administrer Docker et Docker Compose.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 6,
    index: 2,
    paths: ["docker", "decouverte_docker.mdx"],
    label: "Découverte Docker",
    slug: "decouverte_docker",
    course_id: 2,
    description: "Introduction aux concepts fondamentaux de Docker.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 7,
    index: 3,
    paths: ["docker", "installer_docker.mdx"],
    label: "Installer Docker",
    slug: "installer_docker",
    course_id: 2,
    description:
      "Procédure d'installation et de vérification de Docker sur Ubuntu.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 8,
    index: 4,
    paths: ["docker", "les_images.mdx"],
    label: "Les images",
    slug: "les_images",
    course_id: 2,
    description: "Principes et usages des images Docker.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 9,
    index: 5,
    paths: ["docker", "volumes.mdx"],
    label: "Les volumes",
    slug: "volumes",
    course_id: 2,
    description: "Persistance et partage des données avec les volumes Docker.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 10,
    index: 6,
    paths: ["docker", "docker_file.mdx"],
    label: "Dockerfile",
    slug: "docker_file",
    course_id: 2,
    description: "Création d'un Dockerfile pas à pas.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 11,
    index: 7,
    paths: ["docker", "docker_compose.mdx"],
    label: "Docker Compose",
    slug: "docker_compose",
    course_id: 2,
    description: "Orchestration de plusieurs services avec Docker Compose.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 12,
    index: 1,
    paths: ["git", "git_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "git_commandes_utiles",
    course_id: 3,
    description:
      "Commandes principales pour administrer Git et son versionnement.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 13,
    index: 2,
    paths: ["git", "installer_git.mdx"],
    label: "Installer Git",
    slug: "installer_git",
    course_id: 3,
    description:
      "Installation et configuration initiale de Git et mise en place des clés SSH.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 14,
    index: 3,
    paths: ["git", "commit_et_push.mdx"],
    label: "Commit et push",
    slug: "commit_et_push",
    course_id: 3,
    description:
      "Guide pas à pas pour initialiser un dépôt, effectuer ses premiers commits et gérer les branches.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 15,
    index: 1,
    paths: ["php_poo", "syntaxe_base.mdx"],
    label: "Syntaxe de base",
    slug: "syntaxe_base",
    course_id: 6,
    description: "Introduction aux concepts fondamentaux de la POO en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 16,
    index: 7,
    paths: ["php_poo", "auto_chargement.mdx"],
    label: "Auto-chargement de classes",
    slug: "auto_chargement",
    course_id: 6,
    description: "Guide sur l'auto-chargement des classes en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 17,
    index: 3,
    paths: ["php_poo", "constructeur_descructeur.mdx"],
    label: "Constructeur et destructeur",
    slug: "constructeur_descructeur",
    course_id: 6,
    description:
      "Les méthodes constructeur et destructeur dans les classes PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 18,
    index: 2,
    paths: ["php_poo", "visibilite.mdx"],
    label: "Visibilité",
    slug: "visibilite",
    course_id: 6,
    description:
      "Les différents niveaux de visibilité des propriétés et méthodes en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 19,
    index: 4,
    paths: ["php_poo", "heritage.mdx"],
    label: "Héritage",
    slug: "heritage",
    course_id: 6,
    description: "Principes de l'héritage en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 20,
    index: 5,
    paths: ["php_poo", "interfaces.mdx"],
    label: "Interfaces",
    slug: "interfaces",
    course_id: 6,
    description: "Utilisation des interfaces pour définir des contrats en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 21,
    index: 6,
    paths: ["php_poo", "traits.mdx"],
    label: "Traits",
    slug: "traits",
    course_id: 6,
    description: "Utilisation des traits pour le réemploi de code en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 22,
    index: 1,
    paths: ["poo_concepts", "quatre_piliers_poo.mdx"],
    label: "Les quatre pilier de la POO",
    slug: "quatre_pilier_poo",
    course_id: 5,
    description:
      "Les concepts fondamentaux de la programmation orientée objet.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 23,
    index: 2,
    paths: ["poo_concepts", "principes_solid.mdx"],
    label: "Les principes SOLID",
    slug: "principes_solid",
    course_id: 5,
    description: "Les principes de conceptions SOLID illustrés.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 24,
    index: 1,
    paths: ["api_rest", "fondamentaux_rest.mdx"],
    label: "Architecture REST",
    slug: "fondamentaux_rest",
    course_id: 4,
    description: "Introduction, cas d’usages et contraintes architecturales.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 25,
    index: 2,
    paths: ["api_rest", "protocole_http.mdx"],
    label: "Protocole HTTP",
    slug: "protocole_http",
    course_id: 4,
    description: "Structure des requêtes et réponses HTTP, méthodes et codes de statut.",
    created: "1 février 2026",
    updated: "17 mars 2026",
  },
  {
    id: 26,
    index: 3,
    paths: ["api_rest", "conception_routes.mdx"],
    label: "Conception des routes",
    slug: "conception_routes",
    course_id: 4,
    description: "Conventions de nommage des routes, versionnement et gestion du filtrage, tri et pagination.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 27,
    index: 4,
    paths: ["api_rest", "securite_api.mdx"],
    label: "Sécurité des API",
    slug: "securite_api",
    course_id: 4,
    description: "Focus sur l'authentification, les CORS et autres éléments de sécurité.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 28,
    index: 5,
    paths: ["api_rest", "performances_scalabilite.mdx"],
    label: "Performances et scalabilité",
    slug: "performances_scalabilite",
    course_id: 4,
    description: "Cache HTTP, système en couches et autres mécanismes améliorant les performances.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 29,
    index: 1,
    paths: ["php_tests", "trois_familles_tests.mdx"],
    label: "Les familles de tests",
    slug: "trois_familles_tests",
    course_id: 7,
    description:
      "Découvrir les trois grandes familles de tests : unitaires, fonctionnels et end-to-end (E2E).",
    created: "18 mars 2026",
    updated: "18 mars 2026",
  },
  {
    id: 30,
    index: 2,
    paths: ["php_tests", "outils_qualite.mdx"],
    label: "Outils qualité",
    slug: "outils_qualite",
    course_id: 7,
    description:
      "Analyse statique et standards de code avec PHPStan, PHP_CodeSniffer et GrumPHP.",
    created: "18 mars 2026",
    updated: "18 mars 2026",
  },
  {
    id: 32,
    index: 3,
    paths: ["poo_concepts", "architecture_mvc_simple.mdx"],
    label: "Architecture MVC simple",
    slug: "architecture_mvc_simple",
    course_id: 5,
    description: "Découverte de l'architecture MVC et de ses composants.",
    created: "1 février 2026",
    updated: "19 mars 2026",
  },
  {
    id: 31,
    index: 4,
    paths: ["poo_concepts", "architecture_mvc_avancee.mdx"],
    label: "Architecture MVC avancée",
    slug: "architecture_mvc_avancee",
    course_id: 5,
    description:
      "Amélioration d'une architecture MVC simple.",
    created: "1 février 2026",
    updated: "19 mars 2026",
  },
  {
    id: 33,
    index: 1,
    paths: ["elasticsearch", "introduction_elasticsearch.mdx"],
    label: "Introduction",
    slug: "introduction_elasticsearch",
    course_id: 8,
    description:
      "Positionnement d'Elasticsearch face aux bases relationnelles et principaux cas d'usage.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 34,
    index: 2,
    paths: ["elasticsearch", "concepts_fondamentaux.mdx"],
    label: "Concepts fondamentaux",
    slug: "concepts_fondamentaux",
    course_id: 8,
    description:
      "Index, document, mapping et types de champs : les briques de base d'Elasticsearch.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 35,
    index: 3,
    paths: ["elasticsearch", "denormalisation.mdx"],
    label: "La dénormalisation",
    slug: "denormalisation",
    course_id: 8,
    description:
      "Pourquoi Elasticsearch embarque les relations plutôt que de faire des JOIN.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 36,
    index: 4,
    paths: ["elasticsearch", "les_queries.mdx"],
    label: "Les queries",
    slug: "les_queries",
    course_id: 8,
    description:
      "Full-text, term/filter et BoolQuery (must, should, must_not, filter).",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 37,
    index: 5,
    paths: ["elasticsearch", "les_agregations.mdx"],
    label: "Les agrégations",
    slug: "les_agregations",
    course_id: 8,
    description:
      "Agrégations bucket (Terms, Filter), metric (Sum, Min, Avg) et pipeline.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 38,
    index: 6,
    paths: ["elasticsearch", "dot_notation_nested.mdx"],
    label: "Dot notation et nested",
    slug: "dot_notation_nested",
    course_id: 8,
    description:
      "Accès aux champs d'objets imbriqués avec la dot notation et le type nested.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 39,
    index: 7,
    paths: ["elasticsearch", "mapping_fos_elastica.mdx"],
    label: "Mapping FOS Elastica",
    slug: "mapping_fos_elastica",
    course_id: 8,
    description:
      "Comment FOS Elastica se traduit en mapping Elasticsearch et ce que chaque type implique.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 40,
    index: 8,
    paths: ["elasticsearch", "introduction_logstash.mdx"],
    label: "Introduction Logstash",
    slug: "introduction_logstash",
    course_id: 8,
    description:
      "Architecture d'un pipeline Logstash et position dans la stack ELK.",
    created: "26 mars 2026",
    updated: "26 mars 2026",
  },
  {
    id: 41,
    index: 9,
    paths: ["elasticsearch", "introduction_kibana.mdx"],
    label: "Introduction Kibana",
    slug: "introduction_kibana",
    course_id: 8,
    description:
      "Les outils Kibana pour explorer et visualiser les données Elasticsearch.",
    created: "26 mars 2026",
    updated: "26 mars 2026",
  },
  {
    id: 42,
    index: 1,
    paths: ["php_cache", "fondamentaux_cache.mdx"],
    label: "Fondamentaux du cache",
    slug: "fondamentaux_cache",
    course_id: 9,
    description:
      "Cache hit, cache miss, TTL et types de cache : les concepts fondamentaux avant de mettre les mains dans le code.",
    created: "11 juin 2026",
    updated: "11 juin 2026",
  },
  {
    id: 43,
    index: 2,
    paths: ["php_cache", "opcache.mdx"],
    label: "OPcache",
    slug: "opcache",
    course_id: 9,
    description:
      "Cache du bytecode PHP : fonctionnement, configuration et bonnes pratiques de déploiement.",
    created: "11 juin 2026",
    updated: "11 juin 2026",
  },
  {
    id: 44,
    index: 3,
    paths: ["php_cache", "cache_http.mdx"],
    label: "Cache HTTP",
    slug: "cache_http",
    course_id: 9,
    description:
      "ETag, Last-Modified, Cache-Control et Vary : éviter de renvoyer des données inchangées via les headers HTTP.",
    created: "11 juin 2026",
    updated: "11 juin 2026",
  },
  {
    id: 45,
    index: 4,
    paths: ["php_cache", "php_fpm_fastcgi.mdx"],
    label: "PHP-FPM et FastCGI",
    slug: "php_fpm_fastcgi",
    course_id: 9,
    description:
      "Processus persistants avec PHP-FPM et cache de réponses complètes avec le cache FastCGI de Nginx.",
    created: "11 juin 2026",
    updated: "11 juin 2026",
  },
  {
    id: 46,
    index: 5,
    paths: ["php_cache", "redis.mdx"],
    label: "Cache applicatif avec Redis",
    slug: "redis_cache",
    course_id: 9,
    description:
      "Connexion, opérations de base et pattern cache-aside avec Redis en PHP.",
    created: "11 juin 2026",
    updated: "11 juin 2026",
  },
  {
    id: 47,
    index: 6,
    paths: ["php_cache", "invalidation.mdx"],
    label: "Stratégies d'invalidation",
    slug: "invalidation_cache",
    course_id: 9,
    description:
      "TTL, invalidation active, versionnement de clés et cache tags : choisir la bonne stratégie selon le cas.",
    created: "11 juin 2026",
    updated: "11 juin 2026",
  },
  {
    id: 48,
    index: 1,
    paths: ["symfony", "cycle_vie_requete.mdx"],
    label: "Cycle de vie d'une requête",
    slug: "cycle_vie_requete",
    course_id: 10,
    description:
      "Du front controller à kernel.terminate : l'architecture événementielle du HttpKernel.",
    created: "12 juin 2026",
    updated: "12 juin 2026",
  },
  {
    id: 49,
    index: 2,
    paths: ["symfony", "conteneur_services.mdx"],
    label: "Conteneur de services",
    slug: "conteneur_services",
    course_id: 10,
    description:
      "Autowiring, tagged iterators, décoration et compilation : le conteneur au service des principes SOLID.",
    created: "12 juin 2026",
    updated: "12 juin 2026",
  },
  {
    id: 50,
    index: 3,
    paths: ["symfony", "evenements_event_dispatcher.mdx"],
    label: "Événements et EventDispatcher",
    slug: "evenements_event_dispatcher",
    course_id: 10,
    description:
      "Listeners, priorités, événements métier et limites du découplage événementiel.",
    created: "12 juin 2026",
    updated: "12 juin 2026",
  },
  {
    id: 51,
    index: 4,
    paths: ["symfony", "doctrine_orm.mdx"],
    label: "Doctrine ORM",
    slug: "doctrine_orm",
    course_id: 10,
    description:
      "Unit of work, problème N+1, hydratation et migrations : Doctrine au-delà du CRUD.",
    created: "12 juin 2026",
    updated: "12 juin 2026",
  },
  {
    id: 52,
    index: 5,
    paths: ["symfony", "securite.mdx"],
    label: "Sécurité",
    slug: "securite_symfony",
    course_id: 10,
    description:
      "Firewalls, authenticators, rôles et voters : séparer authentification et autorisation.",
    created: "12 juin 2026",
    updated: "12 juin 2026",
  },
  {
    id: 53,
    index: 6,
    paths: ["symfony", "messenger.mdx"],
    label: "Messenger",
    slug: "messenger",
    course_id: 10,
    description:
      "Bus de messages, traitements asynchrones, workers, retries et idempotence.",
    created: "12 juin 2026",
    updated: "12 juin 2026",
  },
  {
    id: 54,
    index: 7,
    paths: ["symfony", "sessions_cookies_stateless.mdx"],
    label: "Sessions, cookies et stateless",
    slug: "sessions_cookies_stateless",
    course_id: 10,
    description:
      "Comment l'identité persiste entre requêtes : session côté serveur contre token côté client.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 55,
    index: 8,
    paths: ["symfony", "hachage_mots_de_passe.mdx"],
    label: "Hachage des mots de passe",
    slug: "hachage_mots_de_passe",
    course_id: 10,
    description:
      "bcrypt, argon2, migration transparente des hash et protection contre la force brute.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 56,
    index: 9,
    paths: ["symfony", "authenticator_sur_mesure.mdx"],
    label: "Authenticator sur mesure",
    slug: "authenticator_sur_mesure",
    course_id: 10,
    description:
      "Anatomie complète d'un authenticator, badges personnalisés et cycle d'événements de l'authentification.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 57,
    index: 10,
    paths: ["symfony", "remember_me_login_link.mdx"],
    label: "Remember-me, login link et CSRF",
    slug: "remember_me_login_link",
    course_id: 10,
    description:
      "Les mécanismes d'authentification prêts à l'emploi : persistance, passwordless et protection CSRF.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 58,
    index: 11,
    paths: ["symfony", "jwt_sso.mdx"],
    label: "JWT et SSO",
    slug: "jwt_sso",
    course_id: 10,
    description:
      "JWT pour les API stateless, puis OAuth2 et OpenID Connect pour le login social et le SSO.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 59,
    index: 12,
    paths: ["symfony", "les_bundles.mdx"],
    label: "Les bundles",
    slug: "les_bundles",
    course_id: 10,
    description:
      "Rôle, avantages et anatomie d'un bundle : configuration, services, compiler pass et Symfony Flex.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 60,
    index: 13,
    paths: ["symfony", "outils_dev_debug.mdx"],
    label: "Outils de dev et de debug",
    slug: "outils_dev_debug",
    course_id: 10,
    description:
      "Symfony CLI, Flex, Maker Bundle, Web Profiler et commandes debug : l'outillage du quotidien.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 61,
    index: 14,
    paths: ["symfony", "bundles_incontournables.mdx"],
    label: "Bundles tierces incontournables",
    slug: "bundles_incontournables",
    course_id: 10,
    description:
      "Catalogue commenté : API Platform, EasyAdmin, LexikJWT, VichUploader, Nelmio et autres.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 62,
    index: 15,
    paths: ["symfony", "composants_a_connaitre.mdx"],
    label: "Composants à connaître",
    slug: "composants_a_connaitre",
    course_id: 10,
    description:
      "Console, Form, Validator, Serializer, Mailer, HttpClient et Workflow : les composants du framework.",
    created: "14 juin 2026",
    updated: "14 juin 2026",
  },
  {
    id: 63,
    index: 16,
    paths: ["symfony", "composant_lock.mdx"],
    label: "Le composant Lock",
    slug: "composant_lock",
    course_id: 10,
    description:
      "Gérer les accès concurrents : verrous bloquants, expiration, stores distribués et race conditions.",
    created: "15 juin 2026",
    updated: "15 juin 2026",
  },
  {
    id: 64,
    index: 1,
    paths: ["data_engineer", "introduction_metier_data_engineer.mdx"],
    label: "Introduction au métier",
    slug: "introduction_metier_data_engineer",
    course_id: 11,
    description:
      "Panorama du métier de data engineer : rôle, cycle de vie de la donnée, écosystème d'outils et repères pour un développeur backend qui découvre le domaine.",
    created: "5 août 2026",
    updated: "5 août 2026",
  },
  {
    id: 65,
    index: 2,
    paths: ["data_engineer", "modelisation_dimensionnelle.mdx"],
    label: "Modélisation dimensionnelle",
    slug: "modelisation_dimensionnelle",
    course_id: 11,
    description:
      "Faits, dimensions, schéma en étoile, SCD et opposition Kimball/Inmon : les fondamentaux de la modélisation analytique.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  {
    id: 66,
    index: 3,
    paths: ["data_engineer", "formats_fichiers_serialisation.mdx"],
    label: "Formats de fichiers et sérialisation",
    slug: "formats_fichiers_serialisation",
    course_id: 11,
    description:
      "Row vs columnar, formats texte vs binaires, schéma embarqué et compression : bien choisir le format d'un fichier de données.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  {
    id: 67,
    index: 4,
    paths: ["data_engineer", "oltp_vs_olap.mdx"],
    label: "OLTP vs OLAP",
    slug: "oltp_vs_olap",
    course_id: 11,
    description:
      "Pourquoi une base applicative et un entrepôt analytique répondent à des besoins opposés, et ce que cela implique sur leur modélisation et leur stockage.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  {
    id: 68,
    index: 5,
    paths: ["data_engineer", "batch_vs_streaming.mdx"],
    label: "Batch vs streaming en profondeur",
    slug: "batch_vs_streaming",
    course_id: 11,
    description:
      "Compromis latence/débit, fenêtrage et architectures Lambda et Kappa pour choisir le bon mode de traitement.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  {
    id: 69,
    index: 6,
    paths: ["data_engineer", "traitement_distribue_concepts.mdx"],
    label: "Traitement distribué : les concepts",
    slug: "traitement_distribue_concepts",
    course_id: 11,
    description:
      "MapReduce, partitionnement, data locality et tolérance aux pannes : comprendre ce que fait un moteur comme Spark avant d'en écrire une ligne.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  {
    id: 70,
    index: 7,
    paths: ["data_engineer", "cdc_replication.mdx"],
    label: "CDC et réplication",
    slug: "cdc_replication",
    course_id: 11,
    description:
      "Change Data Capture, journal de transactions et sémantique de livraison : capter les changements d'une source sans la surcharger.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  // Lessons ci-dessous pas encore push en prod, à décommenter au fur et à mesure des push
  /*
  {
    id: 71,
    index: 8,
    paths: ["data_engineer", "qualite_observabilite_donnee.mdx"],
    label: "Qualité et observabilité de la donnée",
    slug: "qualite_observabilite_donnee",
    course_id: 11,
    description:
      "Dimensions de la qualité, data contracts, tests de données et observabilité pour détecter les anomalies avant l'utilisateur métier.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  {
    id: 72,
    index: 9,
    paths: ["data_engineer", "gouvernance_catalogage_donnee.mdx"],
    label: "Gouvernance et catalogage",
    slug: "gouvernance_catalogage_donnee",
    course_id: 11,
    description:
      "Data catalog, data lineage et rôles de gouvernance (owner, steward, CDO) : rendre la donnée d'une organisation découvrable et fiable.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  {
    id: 73,
    index: 10,
    paths: ["data_engineer", "data_mesh_vs_centralise.mdx"],
    label: "Data mesh vs architecture centralisée",
    slug: "data_mesh_vs_centralise",
    course_id: 11,
    description:
      "Les quatre piliers du data mesh face au modèle centralisé classique, et quand chaque approche a réellement du sens.",
    created: "8 août 2026",
    updated: "8 août 2026",
  },
  */
];

export default lessons;
