import { Lesson } from "@/core/types";

const lessons: Lesson[] = [
  {
    id: 1,
    index: 1,
    paths: ["apache", "apache_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "apache_commandes_utiles",
    course_id: 1,
    description:
      "Commandes principales pour administrer et configurer le serveur Apache.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 2,
    index: 2,
    paths: ["apache", "installer_apache.mdx"],
    label: "Installer Apache",
    slug: "installer_apache",
    course_id: 1,
    description:
      "Procédure d'installation et de vérification d'Apache sur Ubuntu.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 3,
    index: 3,
    paths: ["apache", "virtual_host.mdx"],
    label: "Virtual Host",
    slug: "virtual_host",
    course_id: 1,
    description:
      "Guide sur la création et la gestion des Virtual Hosts dans Apache.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 4,
    index: 4,
    paths: ["apache", "htpasswd.mdx"],
    label: "Restriction .htpasswd",
    slug: "htpasswd",
    course_id: 1,
    description:
      "Mise en place d'une authentification basique avec un fichier .htpasswd.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 5,
    index: 1,
    paths: ["docker", "docker_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "docker_commandes_utiles",
    course_id: 2,
    description:
      "Commandes principales pour administrer Docker et Docker Compose.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 6,
    index: 2,
    paths: ["docker", "decouverte_docker.mdx"],
    label: "Découverte Docker",
    slug: "decouverte_docker",
    course_id: 2,
    description: "Introduction aux concepts fondamentaux de Docker.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 7,
    index: 3,
    paths: ["docker", "installer_docker.mdx"],
    label: "Installer Docker",
    slug: "installer_docker",
    course_id: 2,
    description:
      "Procédure d'installation et de vérification de Docker sur Ubuntu.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 8,
    index: 4,
    paths: ["docker", "les_images.mdx"],
    label: "Les images",
    slug: "les_images",
    course_id: 2,
    description: "Principes et usages des images Docker.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 9,
    index: 5,
    paths: ["docker", "volumes.mdx"],
    label: "Les volumes",
    slug: "volumes",
    course_id: 2,
    description: "Persistance et partage des données avec les volumes Docker.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 10,
    index: 6,
    paths: ["docker", "docker_file.mdx"],
    label: "Dockerfile",
    slug: "docker_file",
    course_id: 2,
    description: "Création d'un Dockerfile pas à pas.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 11,
    index: 7,
    paths: ["docker", "docker_compose.mdx"],
    label: "Docker Compose",
    slug: "docker_compose",
    course_id: 2,
    description: "Orchestration de plusieurs services avec Docker Compose.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 12,
    index: 1,
    paths: ["git", "git_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "git_commandes_utiles",
    course_id: 3,
    description:
      "Commandes principales pour administrer Git et son versionnement.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 13,
    index: 2,
    paths: ["git", "installer_git.mdx"],
    label: "Installer Git",
    slug: "installer_git",
    course_id: 3,
    description:
      "Installation et configuration initiale de Git et mise en place des clés SSH.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 14,
    index: 3,
    paths: ["git", "commit_et_push.mdx"],
    label: "Commit et push",
    slug: "commit_et_push",
    course_id: 3,
    description:
      "Guide pas à pas pour initialiser un dépôt, effectuer ses premiers commits et gérer les branches.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 15,
    index: 1,
    paths: ["php_poo", "syntaxe_base.mdx"],
    label: "Syntaxe de base",
    slug: "syntaxe_base",
    course_id: 6,
    description: "Introduction aux concepts fondamentaux de la POO en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 16,
    index: 7,
    paths: ["php_poo", "auto_chargement.mdx"],
    label: "Auto-chargement de classes",
    slug: "auto_chargement",
    course_id: 6,
    description: "Guide sur l'auto-chargement des classes en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 17,
    index: 3,
    paths: ["php_poo", "constructeur_descructeur.mdx"],
    label: "Constructeur et destructeur",
    slug: "constructeur_descructeur",
    course_id: 6,
    description:
      "Les méthodes constructeur et destructeur dans les classes PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 18,
    index: 2,
    paths: ["php_poo", "visibilite.mdx"],
    label: "Visibilité",
    slug: "visibilite",
    course_id: 6,
    description:
      "Les différents niveaux de visibilité des propriétés et méthodes en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 19,
    index: 4,
    paths: ["php_poo", "heritage.mdx"],
    label: "Héritage",
    slug: "heritage",
    course_id: 6,
    description: "Principes de l'héritage en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 20,
    index: 5,
    paths: ["php_poo", "interfaces.mdx"],
    label: "Interfaces",
    slug: "interfaces",
    course_id: 6,
    description: "Utilisation des interfaces pour définir des contrats en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 21,
    index: 6,
    paths: ["php_poo", "traits.mdx"],
    label: "Traits",
    slug: "traits",
    course_id: 6,
    description: "Utilisation des traits pour le réemploi de code en PHP.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 22,
    index: 1,
    paths: ["poo_concepts", "quatre_piliers_poo.mdx"],
    label: "Les quatre pilier de la POO",
    slug: "quatre_pilier_poo",
    course_id: 5,
    description:
      "Les concepts fondamentaux de la programmation orientée objet.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 23,
    index: 2,
    paths: ["poo_concepts", "principes_solid.mdx"],
    label: "Les principes SOLID",
    slug: "principes_solid",
    course_id: 5,
    description: "Les principes de conceptions SOLID illustrés.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 24,
    index: 1,
    paths: ["api_rest", "fondamentaux_rest.mdx"],
    label: "Architecture REST",
    slug: "fondamentaux_rest",
    course_id: 4,
    description: "Introduction, cas d’usages et contraintes architecturales.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 25,
    index: 2,
    paths: ["api_rest", "protocole_http.mdx"],
    label: "Protocole HTTP",
    slug: "protocole_http",
    course_id: 4,
    description: "Structure des requêtes et réponses HTTP, méthodes et codes de statut.",
    created: "1 février 2026",
    updated: "17 mars 2026",
  },
  {
    id: 26,
    index: 3,
    paths: ["api_rest", "conception_routes.mdx"],
    label: "Conception des routes",
    slug: "conception_routes",
    course_id: 4,
    description: "Conventions de nommage des routes, versionnement et gestion du filtrage, tri et pagination.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 27,
    index: 4,
    paths: ["api_rest", "securite_api.mdx"],
    label: "Sécurité des API",
    slug: "securite_api",
    course_id: 4,
    description: "Focus sur l'authentification, les CORS et autres éléments de sécurité.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 28,
    index: 5,
    paths: ["api_rest", "performances_scalabilite.mdx"],
    label: "Performances et scalabilité",
    slug: "performances_scalabilite",
    course_id: 4,
    description: "Cache HTTP, système en couches et autres mécanismes améliorant les performances.",
    created: "1 février 2026",
    updated: "1 février 2026",
  },
  {
    id: 29,
    index: 1,
    paths: ["php_tests", "trois_familles_tests.mdx"],
    label: "Les familles de tests",
    slug: "trois_familles_tests",
    course_id: 7,
    description:
      "Découvrir les trois grandes familles de tests : unitaires, fonctionnels et end-to-end (E2E).",
    created: "18 mars 2026",
    updated: "18 mars 2026",
  },
  {
    id: 30,
    index: 2,
    paths: ["php_tests", "outils_qualite.mdx"],
    label: "Outils qualité",
    slug: "outils_qualite",
    course_id: 7,
    description:
      "Analyse statique et standards de code avec PHPStan, PHP_CodeSniffer et GrumPHP.",
    created: "18 mars 2026",
    updated: "18 mars 2026",
  },
  {
    id: 32,
    index: 3,
    paths: ["poo_concepts", "architecture_mvc_simple.mdx"],
    label: "Architecture MVC simple",
    slug: "architecture_mvc_simple",
    course_id: 5,
    description: "Découverte de l'architecture MVC et de ses composants.",
    created: "1 février 2026",
    updated: "19 mars 2026",
  },
  {
    id: 31,
    index: 4,
    paths: ["poo_concepts", "architecture_mvc_avancee.mdx"],
    label: "Architecture MVC avancée",
    slug: "architecture_mvc_avancee",
    course_id: 5,
    description:
      "Amélioration d'une architecture MVC simple.",
    created: "1 février 2026",
    updated: "19 mars 2026",
  },
  {
    id: 33,
    index: 1,
    paths: ["elasticsearch", "introduction_elasticsearch.mdx"],
    label: "Introduction",
    slug: "introduction_elasticsearch",
    course_id: 8,
    description:
      "Positionnement d'Elasticsearch face aux bases relationnelles et principaux cas d'usage.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 34,
    index: 2,
    paths: ["elasticsearch", "concepts_fondamentaux.mdx"],
    label: "Concepts fondamentaux",
    slug: "concepts_fondamentaux",
    course_id: 8,
    description:
      "Index, document, mapping et types de champs : les briques de base d'Elasticsearch.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 35,
    index: 3,
    paths: ["elasticsearch", "denormalisation.mdx"],
    label: "La dénormalisation",
    slug: "denormalisation",
    course_id: 8,
    description:
      "Pourquoi Elasticsearch embarque les relations plutôt que de faire des JOIN.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 36,
    index: 4,
    paths: ["elasticsearch", "les_queries.mdx"],
    label: "Les queries",
    slug: "les_queries",
    course_id: 8,
    description:
      "Full-text, term/filter et BoolQuery (must, should, must_not, filter).",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 37,
    index: 5,
    paths: ["elasticsearch", "les_agregations.mdx"],
    label: "Les agrégations",
    slug: "les_agregations",
    course_id: 8,
    description:
      "Agrégations bucket (Terms, Filter), metric (Sum, Min, Avg) et pipeline.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 38,
    index: 6,
    paths: ["elasticsearch", "dot_notation_nested.mdx"],
    label: "Dot notation et nested",
    slug: "dot_notation_nested",
    course_id: 8,
    description:
      "Accès aux champs d'objets imbriqués avec la dot notation et le type nested.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 39,
    index: 7,
    paths: ["elasticsearch", "mapping_fos_elastica.mdx"],
    label: "Mapping FOS Elastica",
    slug: "mapping_fos_elastica",
    course_id: 8,
    description:
      "Comment FOS Elastica se traduit en mapping Elasticsearch et ce que chaque type implique.",
    created: "24 mars 2026",
    updated: "24 mars 2026",
  },
  {
    id: 40,
    index: 8,
    paths: ["elasticsearch", "introduction_logstash.mdx"],
    label: "Introduction Logstash",
    slug: "introduction_logstash",
    course_id: 8,
    description:
      "Architecture d'un pipeline Logstash et position dans la stack ELK.",
    created: "26 mars 2026",
    updated: "26 mars 2026",
  },
  {
    id: 41,
    index: 9,
    paths: ["elasticsearch", "introduction_kibana.mdx"],
    label: "Introduction Kibana",
    slug: "introduction_kibana",
    course_id: 8,
    description:
      "Les outils Kibana pour explorer et visualiser les données Elasticsearch.",
    created: "26 mars 2026",
    updated: "26 mars 2026",
  },
];

export default lessons;
