import {
  Course,
  Lesson,
  LessonReference,
  Reference,
  Register,
} from "./core/types";

const lessons: Lesson[] = [
  {
    id: 1,
    index: 1,
    paths: ["apache", "apache_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "apache_commandes_utiles",
    course_id: 1,
    description:
      "Commandes principales pour administrer et configurer le serveur Apache.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 2,
    index: 2,
    paths: ["apache", "installer_apache.mdx"],
    label: "Installer Apache",
    slug: "installer_apache",
    course_id: 1,
    description:
      "Procédure d’installation et de vérification d’Apache sur Ubuntu.",
    created: "2 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 3,
    index: 3,
    paths: ["apache", "virtual_host.mdx"],
    label: "Virtual Host",
    slug: "virtual_host",
    course_id: 1,
    description:
      "Guide sur la création et la gestion des Virtual Hosts dans Apache.",
    created: "2 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 4,
    index: 4,
    paths: ["apache", "htpasswd.mdx"],
    label: "Restriction .htpasswd",
    slug: "htpasswd",
    course_id: 1,
    description:
      "Mise en place d’une authentification basique avec un fichier .htpasswd.",
    created: "2 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 5,
    index: 1,
    paths: ["docker", "docker_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "docker_commandes_utiles",
    course_id: 2,
    description:
      "Commandes principales pour administrer Docker et Docker Compose.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 6,
    index: 2,
    paths: ["docker", "decouverte_docker.mdx"],
    label: "Découverte Docker",
    slug: "decouverte_docker",
    course_id: 2,
    description: "Introduction aux concepts fondamentaux de Docker.",
    created: "5 novembre 2025",
    updated: "5 novembre 2025",
  },
  {
    id: 7,
    index: 3,
    paths: ["docker", "installer_docker.mdx"],
    label: "Installer Docker",
    slug: "installer_docker",
    course_id: 2,
    description:
      "Procédure d’installation et de vérification de Docker sur Ubuntu.",
    created: "5 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 8,
    index: 4,
    paths: ["docker", "les_images.mdx"],
    label: "Les images",
    slug: "les_images",
    course_id: 2,
    description: "Principes et usages des images Docker.",
    created: "2 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 9,
    index: 5,
    paths: ["docker", "volumes.mdx"],
    label: "Les volumes",
    slug: "volumes",
    course_id: 2,
    description: "Persistance et partage des données avec les volumes Docker.",
    created: "2 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 10,
    index: 6,
    paths: ["docker", "docker_file.mdx"],
    label: "Dockerfile",
    slug: "docker_file",
    course_id: 2,
    description: "Création d’un Dockerfile pas à pas.",
    created: "2 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 11,
    index: 7,
    paths: ["docker", "docker_compose.mdx"],
    label: "Docker Compose",
    slug: "docker_compose",
    course_id: 2,
    description: "Orchestration de plusieurs services avec Docker Compose.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 12,
    index: 1,
    paths: ["git", "git_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "git_commandes_utiles",
    course_id: 3,
    description:
      "Commandes principales pour administrer Git et son versionnement.",
    created: "5 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 13,
    index: 2,
    paths: ["git", "installer_git.mdx"],
    label: "Installer Git",
    slug: "installer_git",
    course_id: 3,
    description:
      "Installation et configuration initiale de Git et mise en place des clés SSH.",
    created: "5 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 14,
    index: 3,
    paths: ["git", "commit_et_push.mdx"],
    label: "Commit et push",
    slug: "commit_et_push",
    course_id: 3,
    description:
      "Guide pas à pas pour initialiser un dépôt, effectuer ses premiers commits et gérer les branches.",
    created: "5 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 15,
    index: 1,
    paths: ["php_poo", "syntaxe_base.mdx"],
    label: "Syntaxe de base",
    slug: "syntaxe_base",
    course_id: 4,
    description: "Introduction aux concepts fondamentaux de la POO en PHP.",
    created: "7 novembre 2025",
    updated: "7 novembre 2025",
  },
  {
    id: 16,
    index: 7,
    paths: ["php_poo", "auto_chargement.mdx"],
    label: "Auto-chargement de classes",
    slug: "auto_chargement",
    course_id: 4,
    description: "Guide sur l'auto-chargement des classes en PHP.",
    created: "9 novembre 2025",
    updated: "9 novembre 2025",
  },
  {
    id: 17,
    index: 3,
    paths: ["php_poo", "constructeur_descructeur.mdx"],
    label: "Constructeur et destructeur",
    slug: "constructeur_descructeur",
    course_id: 4,
    description:
      "Les méthodes constructeur et destructeur dans les classes PHP.",
    created: "9 novembre 2025",
    updated: "9 novembre 2025",
  },
  {
    id: 18,
    index: 2,
    paths: ["php_poo", "visibilite.mdx"],
    label: "Visibilité",
    slug: "visibilite",
    course_id: 4,
    description:
      "Les différents niveaux de visibilité des propriétés et méthodes en PHP.",
    created: "9 novembre 2025",
    updated: "9 novembre 2025",
  },
  {
    id: 19,
    index: 4,
    paths: ["php_poo", "heritage.mdx"],
    label: "Héritage",
    slug: "heritage",
    course_id: 4,
    description: "Principes de l’héritage en PHP.",
    created: "9 novembre 2025",
    updated: "9 novembre 2025",
  },
  {
    id: 20,
    index: 5,
    paths: ["php_poo", "interfaces.mdx"],
    label: "Interfaces",
    slug: "interfaces",
    course_id: 4,
    description: "Utilisation des interfaces pour définir des contrats en PHP.",
    created: "10 novembre 2025",
    updated: "10 novembre 2025",
  },
  {
    id: 21,
    index: 6,
    paths: ["php_poo", "traits.mdx"],
    label: "Traits",
    slug: "traits",
    course_id: 4,
    description: "Utilisation des traits pour le réemploi de code en PHP.",
    created: "10 novembre 2025",
    updated: "10 novembre 2025",
  },
];

const courses: Course[] = [
  {
    id: 1,
    label: "Apache",
    slug: "apache",
    emoji: "/emoji/feather.png",
  },
  {
    id: 2,
    label: "Docker",
    slug: "docker",
    emoji: "/emoji/whale.png",
  },
  {
    id: 3,
    label: "Git",
    slug: "git",
    emoji: "/emoji/octopus.png",
  },
  {
    id: 4,
    label: "PHP POO",
    slug: "php_poo",
    emoji: "/emoji/elephant.png",
  },
];

const references: Reference[] = [
  {
    id: 1,
    label: "PHP - Syntaxe de base",
    url: "https://www.php.net/manual/fr/language.oop5.basic.php",
  },
  {
    id: 2,
    label: "PHP - Mots réservés",
    url: "https://www.php.net/manual/fr/reserved.php",
  },
  {
    id: 3,
    label: "PHP - Propriétés",
    url: "https://www.php.net/manual/fr/language.oop5.properties.php",
  },
  {
    id: 4,
    label: "PHP - Constantes",
    url: "https://www.php.net/manual/fr/language.oop5.constants.php",
  },
  {
    id: 5,
    label: "PHP - Auto-chargement de classes",
    url: "https://www.php.net/manual/fr/language.oop5.autoload.php",
  },
  {
    id: 6,
    label: "PHP - Constructeurs et destructeurs",
    url: "https://www.php.net/manual/fr/language.oop5.decon.php",
  },
  {
    id: 7,
    label: "PHP - Visibilité",
    url: "https://www.php.net/manual/fr/language.oop5.visibility.php",
  },
  {
    id: 8,
    label: "PHP - Héritage",
    url: "https://www.php.net/manual/fr/language.oop5.inheritance.php",
  },
  {
    id: 9,
    label: "PHP - Statique",
    url: "https://www.php.net/manual/fr/language.oop5.static.php",
  },
  {
    id: 10,
    label: "PHP - Abstraction de classes",
    url: "https://www.php.net/manual/fr/language.oop5.abstract.php",
  },
  {
    id: 11,
    label: "PHP - Interfaces",
    url: "https://www.php.net/manual/fr/language.oop5.interfaces.php",
  },
  {
    id: 12,
    label: "PHP - Traits",
    url: "https://www.php.net/manual/fr/language.oop5.traits.php",
  },
  {
    id: 13,
    label: "Git - Documentation officielle",
    url: "https://git-scm.com/docs",
  },
  {
    id: 14,
    label: "Git - Installer Git",
    url: "https://git-scm.com/install",
  },
  {
    id: 15,
    label: "Git - Démarrer avec Git",
    url: "https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control",
  },
  {
    id: 16,
    label: "Git - Démarrer avec un répertoire Git",
    url: "https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository",
  },
  {
    id: 17,
    label: "Docker - Les volumes",
    url: "https://docs.docker.com/engine/storage/volumes/",
  },
  {
    id: 18,
    label: "Docker - Les images",
    url: "https://docs.docker.com/engine/reference/commandline/pull/",
  },
  {
    id: 19,
    label: "Docker - Documentation officielle",
    url: "https://docs.docker.com",
  },
  {
    id: 20,
    label: "Microsoft - Installer WSL",
    url: "https://learn.microsoft.com/fr-fr/windows/wsl/install",
  },
  {
    id: 21,
    label: "Docker - Dockerfile",
    url: "https://docs.docker.com/reference/dockerfile/",
  },
  {
    id: 22,
    label: "Docker - Docker Hub",
    url: "https://hub.docker.com/",
  },
  {
    id: 23,
    label: "Docker - Docker Compose",
    url: "https://docs.docker.com/compose/",
  },
  {
    id: 24,
    label: "Apache - Virtual Hosts",
    url: "https://httpd.apache.org/docs/2.2/fr/vhosts/examples.html",
  },
  {
    id: 25,
    label: "Ubuntu - Installer et configurer Apache",
    url: "https://doc.ubuntu-fr.org/apache2",
  },
  {
    id: 26,
    label: "Apache - htpasswd",
    url: "https://httpd.apache.org/docs/2.4/fr/programs/htpasswd.html",
  },
];

const lesson_references: LessonReference[] = [
  { lesson_id: 15, reference_id: 1 },
  { lesson_id: 15, reference_id: 2 },
  { lesson_id: 15, reference_id: 3 },
  { lesson_id: 15, reference_id: 4 },
  { lesson_id: 16, reference_id: 5 },
  { lesson_id: 17, reference_id: 6 },
  { lesson_id: 18, reference_id: 7 },
  { lesson_id: 19, reference_id: 8 },
  { lesson_id: 15, reference_id: 9 },
  { lesson_id: 19, reference_id: 10 },
  { lesson_id: 20, reference_id: 11 },
  { lesson_id: 21, reference_id: 12 },
  { lesson_id: 15, reference_id: 7 },
  { lesson_id: 12, reference_id: 13 },
  { lesson_id: 13, reference_id: 14 },
  { lesson_id: 14, reference_id: 15 },
  { lesson_id: 13, reference_id: 15 },
  { lesson_id: 13, reference_id: 16 },
  { lesson_id: 14, reference_id: 16 },
  { lesson_id: 9, reference_id: 17 },
  { lesson_id: 8, reference_id: 18 },
  { lesson_id: 5, reference_id: 19 },
  { lesson_id: 6, reference_id: 19 },
  { lesson_id: 7, reference_id: 19 },
  { lesson_id: 7, reference_id: 20 },
  { lesson_id: 10, reference_id: 21 },
  { lesson_id: 10, reference_id: 22 },
  { lesson_id: 11, reference_id: 22 },
  { lesson_id: 11, reference_id: 23 },
  { lesson_id: 3, reference_id: 24 },
  { lesson_id: 2, reference_id: 25 },
  { lesson_id: 4, reference_id: 26 },
];

const register: Register = { courses, lessons, references, lesson_references };

export default register;
