import { Course, Lesson, Register } from "./core/types";

const lessons: Lesson[] = [
  {
    id: 1,
    index: 1,
    paths: ["apache", "apache_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "apache_commandes_utiles",
    course_id: 1,
    description:
      "Commandes principales pour administrer et configurer le serveur Apache.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 2,
    index: 2,
    paths: ["apache", "installer_apache.mdx"],
    label: "Installer Apache",
    slug: "installer_apache",
    course_id: 1,
    description:
      "Procédure d’installation et de vérification d’Apache sur Ubuntu.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 3,
    index: 3,
    paths: ["apache", "virtual_host.mdx"],
    label: "Virtual Host",
    slug: "virtual_host",
    course_id: 1,
    description:
      "Guide sur la création et la gestion des Virtual Hosts dans Apache.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 4,
    index: 4,
    paths: ["apache", "htpasswd.mdx"],
    label: "Restriction .htpasswd",
    slug: "htpasswd",
    course_id: 1,
    description:
      "Mise en place d’une authentification basique avec un fichier .htpasswd.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 5,
    index: 1,
    paths: ["docker", "docker_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "docker_commandes_utiles",
    course_id: 2,
    description:
      "Commandes principales pour administrer Docker et Docker Compose.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 6,
    index: 2,
    paths: ["docker", "decouverte_docker.mdx"],
    label: "Découverte Docker",
    slug: "decouverte_docker",
    course_id: 2,
    description: "Introduction aux concepts fondamentaux de Docker.",
    created: "5 novembre 2025",
    updated: "5 novembre 2025",
  },
  {
    id: 7,
    index: 3,
    paths: ["docker", "installer_docker.mdx"],
    label: "Installer Docker",
    slug: "installer_docker",
    course_id: 2,
    description:
      "Procédure d’installation et de vérification de Docker sur Ubuntu.",
    created: "5 novembre 2025",
    updated: "5 novembre 2025",
  },
  {
    id: 8,
    index: 4,
    paths: ["docker", "les_images.mdx"],
    label: "Les images",
    slug: "les_images",
    course_id: 2,
    description: "Principes et usages des images Docker.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 9,
    index: 5,
    paths: ["docker", "volumes.mdx"],
    label: "Les volumes",
    slug: "volumes",
    course_id: 2,
    description: "Persistance et partage des données avec les volumes Docker.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 10,
    index: 6,
    paths: ["docker", "docker_file.mdx"],
    label: "Dockerfile",
    slug: "docker_file",
    course_id: 2,
    description: "Création d’un Dockerfile pas à pas.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 11,
    index: 7,
    paths: ["docker", "docker_compose.mdx"],
    label: "Docker Compose",
    slug: "docker_compose",
    course_id: 2,
    description: "Orchestration de plusieurs services avec Docker Compose.",
    created: "2 novembre 2025",
    updated: "2 novembre 2025",
  },
  {
    id: 12,
    index: 1,
    paths: ["git", "git_commandes_utiles.mdx"],
    label: "Commandes utiles",
    slug: "git_commandes_utiles",
    course_id: 3,
    description:
      "Commandes principales pour administrer Git et son versionnement.",
    created: "5 novembre 2025",
    updated: "5 novembre 2025",
  },
  {
    id: 13,
    index: 2,
    paths: ["git", "installer_git.mdx"],
    label: "Installer Git",
    slug: "installer_git",
    course_id: 3,
    description:
      "Installation et configuration initiale de Git et mise en place des clés SSH.",
    created: "5 novembre 2025",
    updated: "5 novembre 2025",
  },
  {
    id: 14,
    index: 3,
    paths: ["git", "commit_et_push.mdx"],
    label: "Commit et push",
    slug: "commit_et_push",
    course_id: 3,
    description:
      "Guide pas à pas pour initialiser un dépôt, effectuer ses premiers commits et gérer les branches.",
    created: "5 novembre 2025",
    updated: "5 novembre 2025",
  },
  {
    id: 15,
    index: 1,
    paths: ["php_poo", "syntaxe_base.mdx"],
    label: "Syntaxe de base",
    slug: "syntaxe_base",
    course_id: 4,
    description: "Introduction aux concepts fondamentaux de la POO en PHP.",
    created: "7 novembre 2025",
    updated: "7 novembre 2025",
  },
  {
    id: 16,
    index: 4,
    paths: ["php_poo", "auto_chargement.mdx"],
    label: "Auto-chargement de classes",
    slug: "auto_chargement",
    course_id: 4,
    description: "Guide sur l'auto-chargement des classes en PHP.",
    created: "9 novembre 2025",
    updated: "9 novembre 2025",
  },
  {
    id: 17,
    index: 3,
    paths: ["php_poo", "constructeur_descructeur.mdx"],
    label: "Constructeur et destructeur",
    slug: "constructeur_descructeur",
    course_id: 4,
    description:
      "Les méthodes constructeur et destructeur dans les classes PHP.",
    created: "9 novembre 2025",
    updated: "9 novembre 2025",
  },
  {
    id: 18,
    index: 2,
    paths: ["php_poo", "visibilite.mdx"],
    label: "Visibilité",
    slug: "visibilite",
    course_id: 4,
    description:
      "Les différents niveaux de visibilité des propriétés et méthodes en PHP.",
    created: "9 novembre 2025",
    updated: "9 novembre 2025",
  },
];

const courses: Course[] = [
  {
    id: 1,
    label: "Apache",
    slug: "apache",
    emoji: "/emoji/feather.png",
  },
  {
    id: 2,
    label: "Docker",
    slug: "docker",
    emoji: "/emoji/whale.png",
  },
  {
    id: 3,
    label: "Git",
    slug: "git",
    emoji: "/emoji/octopus.png",
  },
  {
    id: 4,
    label: "PHP POO",
    slug: "php_poo",
    emoji: "/emoji/elephant.png",
  },
];

const register: Register = { courses, lessons };

export default register;
